name: Release merged
on:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  BASE_NAME: ${{ github.head_ref }}

jobs:
  draft_release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.ACTIONS_SUPPORTER_APP_ID }}
          private_key: ${{ secrets.ACTIONS_SUPPORTER_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set tag name
        run: |
          version=${BASE_NAME#release/}
          echo "version=$version"
          echo "TAG_NAME=$version" >> $GITHUB_ENV

      - name: merge to dev
        run: |
          git checkout -t origin/dev
          git merge --no-edit --no-ff main
          git push
          git checkout main

      - name: Tag version
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          draft: true
          generate_release_notes: true
